export const INSIGHTS = [
  "You're not scared of the next level; you're scared of what you'll have to release to reach it.",
  "Most people don't lack strategy; they lack the capacity to hold the results.",
  "Your income rarely exceeds the level your nervous system considers normal.",
  "The real reason you keep 'reworking' your strategy is because the last one started to work.",
  "Inconsistent income is often just inconsistent identity.",
  "The next level doesn't require more effort. It requires a different version of you.",
  "Most people aren't afraid of failure — they're afraid of the responsibility that comes with success.",
  "When your identity upgrades, your standards upgrade automatically.",
  "Many businesses don't plateau because of the market — they plateau because of the founder.",
  "Your brain will always choose familiarity over expansion unless you train it otherwise.",
  "Stop waiting to feel ready. Readiness is a feeling your nervous system creates after you've already moved.",
  "Your pricing is a direct reflection of your self-concept, not just your market research.",
  "The gap between where you are and where you want to be is not a skill gap. It's usually an identity gap.",
  "Boundaries are not walls — they are the edges of what you will hold.",
  "Most 'strategy problems' are actually identity problems wearing business clothes.",
  "Your capacity for receiving sets the upper limit on everything else in your business.",
  "Growth rarely feels like growth while it's happening. It usually feels like discomfort and uncertainty.",
  "The version of you that built what you have cannot be the version that scales it.",
  "You don't need more confidence. You need more evidence that you can handle the unknown.",
  "Charging more is often the most generous thing you can do — it filters for the most committed clients.",
  "The clients you attract are always a match for the identity you're running.",
  "Your business is not separate from your nervous system. They are the same system.",
  "You will attract the level of success your subconscious considers safe.",
  "Every upper limit is just a boundary where your old identity ends.",
  "The content that feels risky to post is usually the content that converts.",
  "You don't need more ideas. You need to fully execute the ones you already have.",
  "If your income has plateaued, look at your self-concept before your strategy.",
  "The version of you that plays small is protecting something. Find out what.",
  "Most procrastination is just fear wearing a productivity mask.",
  "Your relationship with money mirrors your relationship with self-worth.",
  "The goal isn't to be fearless — it's to take the action anyway.",
  "Scaling a business first requires scaling the person running it.",
  "What you tolerate in your business tells the world exactly what you believe you deserve.",
  "Your audience doesn't just buy your product. They buy your certainty about it.",
  "The most powerful thing you can do for your business is to believe in it more than anyone else does.",
  "Inconsistency is often just a nervous system response, not a discipline problem.",
  "You will always self-sabotage at the exact edge of your current capacity.",
  "Visibility isn't just a strategy — it's an identity declaration.",
  "What you call 'overthinking' is often your nervous system's way of protecting old identity.",
  "The version of you who has everything you want doesn't wonder if she's worthy of it.",
  "Your results will match your private narrative about yourself, not your public one.",
  "The day you stop needing external validation is the day your business starts to feel like freedom.",
  "You can't build a six-figure business from a minimum-wage self-concept.",
  "Everything you're avoiding is the exact place your next level lives.",
  "Discipline without identity is just willpower, and willpower always runs out.",
  "Your clients can feel your confidence or your doubt before a word is spoken.",
  "You don't need permission to be the most expensive option in the room.",
  "The version of you that worries about what people think will never build what you know you're capable of.",
  "Your income ceiling is usually set by what you believe is 'normal' for someone like you.",
  "The gap between wanting success and having it is usually just a conversation you haven't had with yourself yet.",
  "Most people are not at capacity with what they know. They're at capacity with who they believe they are.",
  "Selling from conviction is a completely different energy than selling from need.",
  "The moment you decide you're already the person who has what you want, everything shifts.",
  "Your community will be exactly as committed as you are to your own message.",
  "A business built on hustle will always plateau at the edge of your energy.",
  "The biggest risk is not launching the imperfect thing — it's waiting for perfect and never launching at all.",
  "When you align your identity with your goal, strategy becomes obvious.",
  "Playing small doesn't protect you from criticism. It just guarantees mediocrity.",
  "You can't out-strategy a broken self-concept.",
  "Most mindset work isn't about becoming someone new — it's about removing what isn't you.",
  "The thing you're most afraid to say out loud is usually your most powerful positioning.",
  "Revenue follows resonance. When you're fully expressed, sales become easy.",
  "Your audience isn't waiting for more content. They're waiting for your conviction to grow.",
  "The most underrated business skill is knowing when to rest and when to push.",
  "You will always find evidence for the story you're running, whether it's expansive or limiting.",
  "Identity work is not optional at the higher levels. It is the work.",
  "Visibility that comes from insecurity repels. Visibility from certainty attracts.",
  "The woman who scales her business first scales her belief about what's possible.",
  "Your results are not random. They are the sum of your most consistent thoughts.",
  "Stop trying to convince people to buy. Start becoming someone who doesn't need to.",
  "There is a version of you for whom everything you want is completely normal.",
  "Effort without aligned identity is just exhausting.",
  "The more certain you become of your value, the less you need to discount it.",
  "Most 'market research problems' are actually self-worth problems.",
  "You will always expand to fill the container of your self-concept.",
  "The fear of being seen is just the fear of being known — and found worthy anyway.",
  "Every time you charge more and hold your price, you're training your nervous system to receive more.",
  "The version of you who has the business of your dreams isn't working harder — she's working cleaner.",
  "Most people don't lack motivation. They lack a clear identity to move toward.",
  "Your business will always reflect your inner standards, not just your outer goals.",
  "The most revolutionary act in business is to fully believe in your own worth.",
  "Growth that doesn't include identity work will always create chaos at the next level.",
  "Your pattern of undercharging isn't humility — it's a reflection of your self-concept.",
  "The window between an idea and action is where most dreams die.",
  "You cannot build wealth with a poverty mindset, no matter how good the strategy is.",
  "The clearer your identity, the cleaner your offers.",
  "What you're calling 'waiting for the right time' might just be fear of the right time.",
  "Your brand is not what you say it is. It's what your nervous system radiates.",
  "When you fully own your expertise, the words to describe it come naturally.",
  "The version of you that has it all is not more talented — she's more decided.",
  "You don't rise to the level of your goals. You fall to the level of your identity.",
  "Comparison is just your subconscious pointing to an unlived desire.",
  "Every time you stay consistent when you don't want to, your nervous system gets rewired.",
  "The business you're building is always a reflection of the woman you're becoming.",
  "Your best clients will always mirror your highest self-concept, not your lowest.",
  "Charging what you're worth is not arrogance — it's integrity.",
  "When you fully embody your next level, your current level starts to feel too small.",
  "The version of you who has made it doesn't wait to be chosen — she chooses herself first.",
  "Most people plateau because they mistake their comfort zone for their limit.",
  "The fastest way to level up your income is to level up your identity first.",
  "Every time you normalise receiving, you expand your capacity for more.",
  "Your self-doubt is not wisdom. It's just a habit you haven't questioned yet.",
  "The version of you at the next level has already decided she deserves to be there.",
  "You can't build a premium brand from a discounted self-concept.",
  "Clarity is not found. It's built — through action, reflection, and repetition.",
  "The gap between knowing and doing is always an identity gap.",
  "Most 'burnout' is the result of trying to succeed as a version of yourself you've already outgrown.",
  "Your most powerful marketing strategy is your genuine belief in your own transformation.",
  "The patterns that made you successful at one level will hold you back at the next.",
  "Every time you expand your self-concept, your market expands with it.",
  "The version of you that hesitates is not being careful. She's being protective of an old identity.",
  "If your goals don't scare you a little, they might not belong to the next version of you.",
  "The woman who knows her value doesn't negotiate herself down before the conversation even starts.",
  "Clarity isn't the absence of doubt. It's the decision to move anyway.",
  "Momentum is built one aligned decision at a time.",
  "Your energy on a sales call tells the truth that your words try to manage.",
  "When you build from identity, strategy flows. When you build without it, you grind.",
  "The version of you that has everything you want already knows what to do. Listen to her.",
  "You can't create a business beyond the boundaries of your own story.",
  "The most dangerous thing you can do in business is to let your results define your identity.",
  "Consistency is not about motivation. It's about who you've decided to be.",
  "The hardest part of levelling up is not learning the new skills. It's grieving the old version of yourself.",
  "Your next level isn't a strategy upgrade. It's a self-concept upgrade.",
  "What looks like a sales problem is almost always a belief problem.",
  "The version of you that has the freedom you want doesn't need approval to move forward.",
  "Stop optimising for comfort. Start optimising for alignment.",
  "Real confidence isn't about having all the answers. It's about trusting yourself to find them.",
  "The most powerful pivot you can make in your business is to decide you're ready now.",
  "Overflow doesn't come from working more. It comes from becoming the woman who holds more.",
  "Every launch is a mirror. What it reflects is your relationship with your own desire.",
  "Your standards set the floor of what you'll accept — in your business and in your life.",
  "The version of you that's fully expressed doesn't need to chase clients. She attracts them.",
  "Most 'mindset blocks' are not blocks at all. They're signals pointing to unexplored territory.",
  "Building a business that outlasts your hustle starts with building an identity that outlasts your mood.",
  "The woman who leads from her truth will always outperform the woman who leads from her strategy alone.",
  "You don't need to make everything perfect before you start. You need to start to make it perfect.",
  "The version of you that holds a multiple-six-figure business has already made peace with being seen.",
  "Your capacity to receive is always one identity shift ahead of your current results.",
  "Every investment you make in yourself sends a signal to your subconscious about your worth.",
  "The breakthrough you're looking for is not on the other side of the next strategy — it's on the other side of the next identity shift.",
  "Your business grows when you grow. Not the other way around.",
  "Most people don't need more information. They need permission — which only they can give themselves.",
  "The version of you at the top didn't wait for certainty. She manufactured it.",
  "When your standards rise, everything around you either rises with it or falls away.",
  "Scaling your income starts with scaling your belief in the value you create.",
  "The business you've been afraid to build is usually the business you were always meant to build.",
  "Most 'audience growth problems' are actually 'identity expression problems.'",
  "You can't sell from a place of desperation and expect premium results.",
  "The moment you stop asking for permission to occupy your space, everything changes.",
  "The version of you at the next level is not more perfect. She's more decided.",
]

export const getTodaysInsight = () => {
  const now = new Date()
  const start = new Date(now.getFullYear(), 0, 0)
  const diff = now - start
  const oneDay = 1000 * 60 * 60 * 24
  const dayOfYear = Math.floor(diff / oneDay)
  const index = (dayOfYear - 1) % INSIGHTS.length
  return { insight: INSIGHTS[index], number: index + 1 }
}
